### PR TITLE
Issue #30 - Switch from bin directory to snappy package

### PR DESCRIPTION
**Pull request by bytesized**
This commit converts the bin directory to a package named snappy as suggested in Issue #30.

### CODE REVIEW

**Comment by bytesized** [comment]
@willkg Are you available to review this?

**Comment by willkg** [comment]
I can review it. I haven't been able to run the tests so far. I'll try to figure out how to deal with that. Maybe I'll spend some time to throw together a docker container.

I'll try to report back on that by tomorrow.

**Comment by willkg** [comment]
I got a docker container working and was able to pull this down and run the quickstart and the tests. It looks good to me.

r+

Once you land this, I'll create a PR against master with my docker changes. I don't know if it meets your needs, but maybe it'll save you some time.

**Comment by bytesized** [comment]
Thanks. I would appreciate the PR with the docker changes; that would indeed save me some time.

**Pull request merged**
