### PR TITLE
Compress .pdb files on disk with bz2

### LINKED ISSUE #25: Evaluate compressing symbol files
Symbol files tend to compress very well: 80%+ when using `gzip --fast`, possibly much more with more aggressive compression. We should evaluate storing the symbol files in compressed format to disk; it could dramatically increase the effective size of the cache.

### PR DESCRIPTION
**Pull request by willkg**
Fixes #25

### CODE REVIEW

**Comment by willkg** [comment]
I used the approach @rhelmer had in #25. Notes are in the issue.

One caveat is that this project has no tests. While I stood up the server locally and queried it using the example in the MDN docs and I think this change is ok, it's difficult to be sure.

Note: If/When this lands, we'll need to wipe the cache directory on the server before pushing this out.

**Comment by rhelmer** [comment]
Might consider modifying the cache dir path so there can't be a conflict if someone forgets to wipe the cache directory? Otherwise lgtm.

**Comment by willkg** [comment]
The cache dir path comes from configuration. Because of that, I'm not sure I can change it in code along with this change.

**Comment by rhelmer** [comment]
@willkg fair enough. I was thinking maybe appending a `./compressed` subdir or adding a `.bz2` extension.

**Comment by willkg** [comment]
I thought about adding a `.bz2` to the end of the path. We can't change the file extension without changing code that does casual things with `.pdb`.

Because there's no tests and because I don't use this tool myself so I'm not sure I could effectively test it by hand, I'm kind of in a "touch the least amount of stuff" mode.

However, if that's preferred I'll definitely make that change.

**Comment by willkg** [comment]
Actually, this is silly... we should be wiping the cache regardless because otherwise we'll have a bunch of files in the cache that aren't being used and are just taking up space.

**Comment by rhelmer** [comment]
Yeah let's jfdi.

**Comment by rhelmer** [comment]
(that is, let's just ship this, we know there's only one instance right now etc, it might break local dev installs but there aren't many of those)

**Comment by ddurst** [comment]
IINM, and Gabriele should keep me honest, I think the code is already set up to evict things from the cache on an intake-defined interval. That should be what two throttling variables are for (see https://github.com/mozilla/Snappy-Symbolication-Server/pull/9). So, worst case scenario I think is that we adjust those levels to account for the reduced disk space usage.

**Comment by ddurst** [comment]
Do we have any way of determining if this introduces a delay in roundtrip time for request processing?

**Comment by willkg** [comment]
Because there's additional processing (decompressing), I'm sure it introduces a delay when the symbols being looked for aren't in the memory cache but are in the disk cache. I don't know if it'd be noticeable to a user or not. I can't imagine it'd be worse than the case where the server is loading the .sym files from s3 and then parsing them.

I think if this is a concern, the best bet would be to set up a second snappy server on the same infrastructure as the first and then compare the two.

**Comment by ddurst** [comment]
Hmmm. Right now, I don't know of a use case for this that has a return trip to a user (or, at least, not to a non-Mozillian, as I only know of platform and perf devs using this). I'm less concerned about some lag in responding to requests that only affect server/data processing across the board than possibly evicting from the cache too aggressively. But I defer to you: if the eviction methodology in use is currently sufficient (even more so if we DON'T also increase the current disk space (8GB)) when paired with compression, lgtm.

**Comment by ddurst** [comment]
We need metrics for this, but in the meantime, I agree with @willkg: if we're curious about comparison (and especially if we're running via screen), then we should set up another.

In the meantime, we keep running out of disk space, so I say merge on and we'll fix it if it breaks.

**Pull request merged**
