### PR TITLE
Add requirements.txt file and update README

### PR DESCRIPTION
**Pull request by willkg**
Python projects specify their requirements in a requirements.txt file.
This makes it easier to install all the requirements (particularly if
the project has pegged them to specific versions) using pip.

This commit adds a requirements file and updates the README accordingly.

r?

### CODE REVIEW

**Comment by willkg** [comment]
If I had my druthers, I'd convert the README to markdown or restructured text. It makes it easier to read on GitHub and anywhere else that renders the text.

Anyone averse to me doing that here?

**Comment by willkg** [comment]
Also, these are cosmetic changes to ease development. They don't change anything fundamental about the project.

**Comment by ddurst** [comment]
Amen to adding some structure to this beast. r+

**Comment by ddurst** [comment]
<-- does not have merge permissions. @rhelmer ?

**Pull request merged**
